# Generated by Django 2.0.3 on 2018-04-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationofperson',
            name='QQ_num',
        ),
        migrations.RemoveField(
            model_name='informationofperson',
            name='signature',
        ),
    ]
