# Generated by Django 2.0.3 on 2018-04-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180420_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_category', models.IntegerField(choices=[(1, '股份有限公司'), (2, '有限责任公司'), (3, '非公司制企业'), (4, '私营独资企业'), (5, '私营合伙企业'), (6, '其他')], verbose_name='组织类别')),
                ('industry_classification', models.IntegerField(choices=[(1, '农业'), (2, '林业'), (3, '水利'), (4, '电力'), (5, '热力'), (6, '批发'), (7, '住宿'), (8, '采矿业'), (9, '制造业'), (10, '建筑业'), (11, '零售业'), (12, '餐饮业'), (13, '物业管理'), (14, '房地产业'), (15, '信息传输业'), (16, '交通运输业'), (17, '畜牧业和渔业'), (18, '仓诸和邮电业'), (19, '租赁和商务服务业'), (20, '文化、体育和娱乐业'), (21, '科学研究和技术服务业'), (22, '软件和信息技术服务业'), (23, '燃气及水生产和供应业'), (24, '环境和公共设施管理业'), (25, '居民服务、修理和其他服务业'), (26, '其他未列明行业')], verbose_name='产业分类')),
                ('registered_fund', models.CharField(max_length=10, verbose_name='注册资金')),
                ('annual_revenue', models.CharField(max_length=10, verbose_name='企业年营业收入')),
                ('current_number_of_employees', models.CharField(max_length=5, verbose_name='现从业人数')),
                ('college_degree_or_above', models.CharField(max_length=5, verbose_name='大专及以上学历人数')),
                ('intermediate_and_above_titles', models.CharField(max_length=5, verbose_name='中级及以上职称人数')),
                ('info_of_company', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.InformationOfPerson', verbose_name='归属于哪个企业')),
            ],
        ),
    ]
