# Generated by Django 2.0.3 on 2018-04-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_companybasicinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companybasicinfo',
            options={'verbose_name_plural': '企业基本情况管理'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id'], 'verbose_name_plural': '选项管理'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['id'], 'verbose_name_plural': '选择题问题管理'},
        ),
        migrations.AddField(
            model_name='option',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Questionnaire', verbose_name='对应的问卷'),
        ),
    ]
